import streamlit as st

# App title
st.title("London Underground - Stations & Lines")

st.write(
    "Type a station name to see which lines serve it. "
)

# --- line colour snippets ---
CIRCLE = '<span style="color:#FFCE00">Circle</span>'  # yellow
MET = '<span style="color:#9B0058">Metropolitan</span>'  # purple
DISTRICT = '<span style="color:#007D32">District</span>'  # green
PICCADILLY = '<span style="color:#003688">Piccadilly</span>'  # dark blue
HAMMERSMITH_CITY = '<span style="color:#F3A9BB">Hammersmith & City</span>'  # pink
BAKERLOO = '<span style="color:#B36305">Bakerloo</span>'  # brown
NORTHERN = '<span style="color:#000000">Northern</span>'  # black
CENTRAL = '<span style="color:#E32017">Central</span>'  # red
JUBILEE = '<span style="color:#A0A5A9">Jubilee</span>'  # grey
VICTORIA = '<span style="color:#0098D4">Victoria</span>'  # light blue
WATERLOO_CITY = '<span style="color:#93CEBA">Waterloo & City</span>'  # light teal
ELIZABETH = '<span style="color:#9364CC">Elizabeth</span>'  # purple-lilac

# --- your data with Circle & Metropolitan coloured ---
station_lines = {
    "Acton Town": f"{DISTRICT}, {PICCADILLY}",
    "Aldgate": f"{CIRCLE}, {MET}",
    "Aldgate East": f"{DISTRICT}, {HAMMERSMITH_CITY}",
    "Alperton": PICCADILLY,
    "Amersham": MET,
    "Angel": NORTHERN,
    "Archway": NORTHERN,
    "Arnos Grove": PICCADILLY,
    "Arsenal": PICCADILLY,
    "Baker Street": f"{BAKERLOO}, {CIRCLE}, {HAMMERSMITH_CITY}, {MET}",
    "Balham": NORTHERN,
    "Bank": f"{CENTRAL}, {NORTHERN}, {WATERLOO_CITY}",
    "Barbican": f"{CIRCLE}, {HAMMERSMITH_CITY}, {MET}",
    "Barking": f"{DISTRICT}, {HAMMERSMITH_CITY}",
    "Barkingside": CENTRAL,
    "Barons Court": f"{DISTRICT}, {PICCADILLY}",
    "Battersea Power Station": NORTHERN,
    "Bayswater": f"{CIRCLE}, {DISTRICT}",
    "Becontree": DISTRICT,
    "Belsize Park": NORTHERN,
    "Bermondsey": JUBILEE,
    "Bethnal Green": CENTRAL,
    "Blackfriars": f"{CIRCLE}, {DISTRICT}",
    "Blackhorse Road": VICTORIA,
    "Bond Street": f"{CENTRAL}, {JUBILEE}",
    "Borough": NORTHERN,
    "Boston Manor": PICCADILLY,
    "Bounds Green": PICCADILLY,
    "Bow Road": f"{DISTRICT}, {HAMMERSMITH_CITY}",
    "Brent Cross": NORTHERN,
    "Brixton": VICTORIA,
    "Bromley-by-Bow": f"{DISTRICT}, {HAMMERSMITH_CITY}",
    "Buckhurst Hill": CENTRAL,
    "Burnt Oak": NORTHERN,
    "Caledonian Road": PICCADILLY,
    "Camden Town": NORTHERN,
    "Canada Water": JUBILEE,
    "Canary Wharf": JUBILEE,
    "Canning Town": JUBILEE,
    "Cannon Street": f"{CIRCLE}, {DISTRICT}",
    "Canons Park": JUBILEE,
    "Chalfont & Latimer": MET,
    "Chalk Farm": NORTHERN,
    "Chancery Lane": CENTRAL,
    "Charing Cross": f"{BAKERLOO}, {NORTHERN}",
    "Chesham": MET,
    "Chigwell": CENTRAL,
    "Chiswick Park": DISTRICT,
    "Chorleywood": MET,
    "Clapham Common": NORTHERN,
    "Clapham North": NORTHERN,
    "Clapham South": NORTHERN,
    "Cockfosters": PICCADILLY,
    "Colindale": NORTHERN,
    "Colliers Wood": NORTHERN,
    "Covent Garden": PICCADILLY,
    "Croxley": MET,
    "Dagenham East": DISTRICT,
    "Dagenham Heathway": DISTRICT,
    "Debden": CENTRAL,
    "Dollis Hill": JUBILEE,
    "Ealing Broadway": f"{CENTRAL}, {DISTRICT}",
    "Ealing Common": f"{DISTRICT}, {PICCADILLY}",
    "Earl's Court": f"{DISTRICT}, {PICCADILLY}",
    "East Acton": CENTRAL,
    "East Finchley": NORTHERN,
    "East Ham": f"{DISTRICT}, {HAMMERSMITH_CITY}",
    "East Putney": DISTRICT,
    "Eastcote": f"{MET}, {PICCADILLY}",
    "Edgware": NORTHERN,
    "Edgware Road (Circle Line)": f"{CIRCLE}, {DISTRICT}, {HAMMERSMITH_CITY}",
    "Elephant & Castle": f"{BAKERLOO}, {NORTHERN}",
    "Elm Park": DISTRICT,
    "Embankment": f"{BAKERLOO}, {CIRCLE}, {DISTRICT}, {NORTHERN}",
    "Epping": CENTRAL,
    "Euston": f"{NORTHERN}, {VICTORIA}",
    "Euston Square": f"{CIRCLE}, {HAMMERSMITH_CITY}, {MET}",
    "Fairlop": CENTRAL,
    "Farringdon": f"{CIRCLE}, {HAMMERSMITH_CITY}, {MET}",
    "Finchley Central": NORTHERN,
    "Finchley Road": f"{JUBILEE}, {MET}",
    "Finsbury Park": f"{PICCADILLY}, {VICTORIA}",
    "Fulham Broadway": DISTRICT,
    "Gants Hill": CENTRAL,
    "Gloucester Road": f"{CIRCLE}, {DISTRICT}, {PICCADILLY}",
    "Golders Green": NORTHERN,
    "Goldhawk Road": f"{CIRCLE}, {HAMMERSMITH_CITY}",
    "Goodge Street": NORTHERN,
    "Grange Hill": CENTRAL,
    "Great Portland Street": f"{CIRCLE}, {HAMMERSMITH_CITY}, {MET}",
    "Greenford": CENTRAL,
    "Green Park": f"{JUBILEE}, {PICCADILLY}, {VICTORIA}",
    "Gunnersbury": DISTRICT,
    "Hainault": CENTRAL,
    "Hammersmith (District/Piccadilly)": f"{DISTRICT}, {PICCADILLY}",
    "Hammersmith (H&C/Circle)": f"{CIRCLE}, {HAMMERSMITH_CITY}",
    "Hampstead": NORTHERN,
    "Hanger Lane": CENTRAL,
    "Harlesden": BAKERLOO,
    "Harrow & Wealdstone": BAKERLOO,
    "Harrow-on-the-Hill": MET,
    "Hatton Cross": PICCADILLY,
    "Heathrow Terminals 2 & 3": PICCADILLY,
    "Heathrow Terminal 4": PICCADILLY,
    "Heathrow Terminal 5": PICCADILLY,
    "Hendon Central": NORTHERN,
    "High Barnet": NORTHERN,
    "Highbury & Islington": VICTORIA,
    "Highgate": NORTHERN,
    "High Street Kensington": f"{CIRCLE}, {DISTRICT}",
    "Hillingdon": f"{MET}, {PICCADILLY}",
    "Holborn": f"{CENTRAL}, {PICCADILLY}",
    "Holland Park": CENTRAL,
    "Holloway Road": PICCADILLY,
    "Hornchurch": DISTRICT,
    "Hounslow Central": PICCADILLY,
    "Hounslow East": PICCADILLY,
    "Hounslow West": PICCADILLY,
    "Hyde Park Corner": PICCADILLY,
    "Ickenham": MET,
    "Kennington": NORTHERN,
    "Kensal Green": BAKERLOO,
    "Kensington (Olympia)": DISTRICT,
    "Kentish Town": NORTHERN,
    "Kenton": BAKERLOO,
    "Kew Gardens": DISTRICT,
    "Kilburn": JUBILEE,
    "Kilburn Park": BAKERLOO,
    "Kingsbury": JUBILEE,
    "King's Cross St. Pancras": f"{CIRCLE}, {HAMMERSMITH_CITY}, {MET}, {NORTHERN}, {PICCADILLY}, {VICTORIA}",
    "Knightsbridge": PICCADILLY,
    "Ladbroke Grove": f"{CIRCLE}, {HAMMERSMITH_CITY}",
    "Lambeth North": BAKERLOO,
    "Lancaster Gate": CENTRAL,
    "Latimer Road": f"{CIRCLE}, {HAMMERSMITH_CITY}",
    "Leicester Square": f"{NORTHERN}, {PICCADILLY}",
    "Leyton": CENTRAL,
    "Leytonstone": CENTRAL,
    "Liverpool Street": f"{CENTRAL}, {CIRCLE}, {MET}",
    "London Bridge": f"{JUBILEE}, {NORTHERN}",
    "Loughton": CENTRAL,
    "Maida Vale": BAKERLOO,
    "Manor House": PICCADILLY,
    "Mansion House": f"{CIRCLE}, {DISTRICT}",
    "Marble Arch": CENTRAL,
    "Marylebone": BAKERLOO,
    "Mile End": f"{CENTRAL}, {DISTRICT}, {HAMMERSMITH_CITY}",
    "Mill Hill East": NORTHERN,
    "Monument": f"{CIRCLE}, {DISTRICT}",
    "Moorgate": f"{CIRCLE}, {HAMMERSMITH_CITY}, {MET}, {NORTHERN}",
    "Moor Park": MET,
    "Morden": NORTHERN,
    "Mornington Crescent": NORTHERN,
    "Neasden": JUBILEE,
    "Newbury Park": CENTRAL,
    "Nine Elms": NORTHERN,
    "North Acton": CENTRAL,
    "North Ealing": PICCADILLY,
    "North Greenwich": JUBILEE,
    "North Harrow": MET,
    "North Wembley": BAKERLOO,
    "Northfields": PICCADILLY,
    "Northolt": CENTRAL,
    "Northwick Park": MET,
    "Northwood": MET,
    "Northwood Hills": MET,
    "Notting Hill Gate": f"{CENTRAL}, {CIRCLE}, {DISTRICT}",
    "Oakwood": PICCADILLY,
    "Old Street": NORTHERN,
    "Osterley": PICCADILLY,
    "Oval": NORTHERN,
    "Oxford Circus": f"{BAKERLOO}, {CENTRAL}, {VICTORIA}",
    "Paddington": f"{BAKERLOO}, {CIRCLE}, {DISTRICT}, {HAMMERSMITH_CITY}",
    "Park Royal": PICCADILLY,
    "Parsons Green": DISTRICT,
    "Perivale": CENTRAL,
    "Piccadilly Circus": f"{BAKERLOO}, {PICCADILLY}",
    "Pimlico": VICTORIA,
    "Pinner": MET,
    "Plaistow": f"{DISTRICT}, {HAMMERSMITH_CITY}",
    "Preston Road": MET,
    "Putney Bridge": DISTRICT,
    "Queen's Park": BAKERLOO,
    "Queensbury": JUBILEE,
    "Queensway": CENTRAL,
    "Ravenscourt Park": DISTRICT,
    "Rayners Lane": f"{MET}, {PICCADILLY}",
    "Redbridge": CENTRAL,
    "Regent's Park": BAKERLOO,
    "Richmond": DISTRICT,
    "Rickmansworth": MET,
    "Roding Valley": CENTRAL,
    "Royal Oak": f"{CIRCLE}, {HAMMERSMITH_CITY}",
    "Ruislip": f"{MET}, {PICCADILLY}",
    "Ruislip Gardens": CENTRAL,
    "Ruislip Manor": f"{MET}, {PICCADILLY}",
    "Russell Square": PICCADILLY,
    "St. James's Park": f"{CIRCLE}, {DISTRICT}",
    "St. John's Wood": JUBILEE,
    "St. Paul's": CENTRAL,
    "Seven Sisters": VICTORIA,
    "Shepherd's Bush (Central)": CENTRAL,
    "Shepherd's Bush Market": f"{CIRCLE}, {HAMMERSMITH_CITY}",
    "Sloane Square": f"{CIRCLE}, {DISTRICT}",
    "Snaresbrook": CENTRAL,
    "South Ealing": PICCADILLY,
    "South Harrow": PICCADILLY,
    "South Kensington": f"{CIRCLE}, {DISTRICT}, {PICCADILLY}",
    "South Kenton": BAKERLOO,
    "South Ruislip": CENTRAL,
    "South Wimbledon": NORTHERN,
    "South Woodford": CENTRAL,
    "Southfields": DISTRICT,
    "Southgate": PICCADILLY,
    "Southwark": JUBILEE,
    "Stamford Brook": DISTRICT,
    "Stanmore": JUBILEE,
    "Stepney Green": f"{DISTRICT}, {HAMMERSMITH_CITY}",
    "Stockwell": f"{NORTHERN}, {VICTORIA}",
    "Stonebridge Park": BAKERLOO,
    "Stratford": f"{CENTRAL}, {JUBILEE}",
    "Sudbury Hill": PICCADILLY,
    "Sudbury Town": PICCADILLY,
    "Swiss Cottage": JUBILEE,
    "Temple": f"{CIRCLE}, {DISTRICT}",
    "Theydon Bois": CENTRAL,
    "Tooting Bec": NORTHERN,
    "Tooting Broadway": NORTHERN,
    "Tottenham Court Road": f"{CENTRAL}, {NORTHERN}",
    "Tottenham Hale": VICTORIA,
    "Totteridge & Whetstone": NORTHERN,
    "Turnham Green": f"{DISTRICT}, {PICCADILLY}",
    "Tufnell Park": NORTHERN,
    "Upminster": DISTRICT,
    "Upminster Bridge": DISTRICT,
    "Upton Park": f"{DISTRICT}, {HAMMERSMITH_CITY}",
    "Vauxhall": VICTORIA,
    "Victoria": f"{CIRCLE}, {DISTRICT}, {VICTORIA}",
    "Warren Street": f"{NORTHERN}, {VICTORIA}",
    "Warwick Avenue": BAKERLOO,
    "Watford": MET,
    "Wembley Central": BAKERLOO,
    "Wembley Park": f"{JUBILEE}, {MET}",
    "West Acton": CENTRAL,
    "West Brompton": DISTRICT,
    "West Finchley": NORTHERN,
    "West Ham": f"{DISTRICT}, {HAMMERSMITH_CITY}, {JUBILEE}",
    "West Hampstead": JUBILEE,
    "West Kensington": DISTRICT,
    "West Ruislip": CENTRAL,
    "White City": CENTRAL,
    "Whitechapel": f"{DISTRICT}, {HAMMERSMITH_CITY}",
    "Willesden Green": JUBILEE,
    "Willesden Junction": BAKERLOO,
    "Wimbledon": DISTRICT,
    "Wimbledon Park": DISTRICT,
    "Wood Green": PICCADILLY,
    "Woodford": CENTRAL,
    "Woodside Park": NORTHERN,
}

# Helper for case-insensitive lookup
normalized_map = {name.lower(): name for name in station_lines.keys()}

station_input = st.text_input("Enter station name", "")

if st.button("Search"):
    query = station_input.strip().lower()
    if not query:
        st.warning("Please enter a station name or part of it.")
    else:
        # partial, case-insensitive match over all station names
        matches = {
            name: lines
            for name, lines in station_lines.items()
            if query in name.lower()
        }

        if not matches:
            st.error(
                f"No stations match '{station_input}'. Try another search."
            )

        elif len(matches) == 1:
            # exactly one match: show it prominently (with colours)
            (name, lines), = matches.items()
            st.markdown(
                f"**Lines serving {name}:** {lines}",
                unsafe_allow_html=True,
            )

        else:
            st.info(f"Found {len(matches)} matching stations:")
            for name, lines in sorted(matches.items()):
                st.markdown(
                    f"• <b>{name}</b> – {lines}",
                    unsafe_allow_html=True,
                )
